"""
worker.py — TickerTap background news worker for Server B (REDACTED_HOST).

Main loop:
    1. Flush any pending articles from the local SQLite queue.
    2. Optionally refresh learned scoring rules from Server A.
    3. Fetch news from all 4 sources (Yahoo, Google, Finviz, MarketWatch).
    4. Deduplicate against already-seen URLs (local in-memory set).
    5. For each new article:
       a. Build an LLM prompt with headline + summary + learned rules.
       b. Call the local Ollama API (http://localhost:11434/api/generate).
       c. Parse the structured JSON response.
       d. POST scored article to Server A's internal ingestion endpoint.
       e. On failure → queue to local SQLite for retry.
    6. Sleep (10 min during US market hours, 30 min off-hours).

The worker periodically fetches calibration rules generated by the learner
(learner.py) from Server A.  These rules are injected into the LLM prompt
to improve scoring accuracy over time (AppREDACTED 2 — dynamic system prompt).

Environment variables (set via systemd or .env):
    TICKERTAP_API_URL      — Server A base URL (e.g. http://<APP_IP>:8000)
    TICKERTAP_INTERNAL_KEY — Shared secret for the X-Internal-Key header
    OLLAMA_MODEL           — Ollama model tag (default: llama3:8b-instruct-q4_K_M)
    OLLAMA_URL             — Ollama API base URL (default: http://localhost:11434)

Usage:
    python worker.py
"""

import json
import logging
import os
import re
import sys
import time
from datetime import datetime, timezone
from typing import Optional

import requests

import article_queue
import sources

# ---------------------------------------------------------------------------
# Logging configuration
# ---------------------------------------------------------------------------
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
    handlers=[logging.StreamHandler(sys.stdout)],
)
logger = logging.getLogger("tickertap-worker")

# ---------------------------------------------------------------------------
# Configuration from environment
# ---------------------------------------------------------------------------
API_URL = os.getenv("TICKERTAP_API_URL", "http://localhost:8000")
INTERNAL_KEY = os.getenv("TICKERTAP_INTERNAL_KEY", "")
OLLAMA_MODEL = os.getenv("OLLAMA_MODEL", "llama3:8b-instruct-q4_K_M")
OLLAMA_URL = os.getenv("OLLAMA_URL", "http://localhost:11434")

# Internal ingestion endpoint on Server A.
_INGEST_ENDPOINT = f"{API_URL}/api/v1/news/internal/news"

# Active scoring rules endpoint on Server A (feedback loop).
_RULES_ENDPOINT = f"{API_URL}/api/v1/feedback/internal/rules/active"

# How often to refresh learned scoring rules (every N cycles).
# At 10-min cycles during market hours this is roughly every hour.
_RULES_REFRESH_EVERY = 6

# Sleep intervals in seconds.
_SLEEP_MARKET_HOURS = 600    # 10 minutes
_SLEEP_OFF_HOURS = 1800      # 30 minutes

# Batch size for POSTing to Server A (send in chunks to avoid huge payloads).
_POST_BATCH_SIZE = 10

# Maximum articles to process per cycle to avoid overloading Ollama.
_MAX_ARTICLES_PER_CYCLE = 50

# Ollama generation timeout (LLM can be slow on large prompts).
_OLLAMA_TIMEOUT = 120  # seconds


# ---------------------------------------------------------------------------
# LLM Prompt — base template + dynamic rules injection
# ---------------------------------------------------------------------------

# Base scoring instructions (always included).
_LLM_PROMPT_BASE = """You are a financial news analyst. Analyze this news article and return ONLY valid JSON.

Article headline: {title}
Article summary: {summary}

Return this exact JSON structure:
{{
  "general_score": <integer -5 to +5, where -5 is extremely bearish and +5 is extremely bullish for the overall market>,
  "general_reasoning": "<one sentence explaining the general market impact>",
  "tickers": [
    {{
      "symbol": "<affected stock ticker>",
      "score": <integer -5 to +5 for this specific stock>,
      "reasoning": "<one sentence explaining impact on this stock>"
    }}
  ]
}}

Rules:
- Only include tickers that are directly or significantly affected
- Score 0 means neutral/no impact
- Keep reasoning concise (one sentence max)
- Return valid JSON only, no markdown or explanation"""

# Template for injecting learned calibration rules above the base prompt.
_RULES_SECTION_TEMPLATE = """=== LEARNED SCORING RULES ===
Based on analysis of past prediction accuracy, apply these calibration rules:
{rules_text}
=== END RULES ===

"""


# ---------------------------------------------------------------------------
# Learned rules state (refreshed every _RULES_REFRESH_EVERY cycles)
# ---------------------------------------------------------------------------

# Cached rules text from Server A (None = never fetched, "" = no active rules).
_cached_rules_text: Optional[str] = None

# Cycle counter for rules refresh (fetches on first cycle, then every N).
_rules_refresh_counter: int = 0


def _fetch_active_rules() -> Optional[str]:
    """Fetch the currently active scoring rules from Server A.

    Calls ``GET /api/v1/feedback/internal/rules/active`` and extracts the
    ``rules_text`` field.  Returns None if no active rules exist or on error.

    Returns:
        The active rules text string, or None if unavailable.
    """
    headers = {"X-Internal-Key": INTERNAL_KEY}
    try:
        resp = requests.get(_RULES_ENDPOINT, headers=headers, timeout=10)
        if resp.status_code == 404:
            # No active rules yet — this is normal before the learner runs.
            logger.info("No active scoring rules on Server A (404).")
            return None
        if resp.status_code != 200:
            logger.warning(
                "Failed to fetch scoring rules: status=%d", resp.status_code
            )
            return None
        rules_text = resp.json().get("rules_text", "")
        if rules_text:
            logger.info(
                "Fetched active scoring rules (v%s, %d chars).",
                resp.json().get("rule_version", "?"),
                len(rules_text),
            )
        return rules_text or None
    except requests.RequestException as exc:
        logger.warning("Could not reach Server A for scoring rules: %s", exc)
        return None


def _maybe_refresh_rules() -> None:
    """Refresh cached scoring rules if the refresh interval has elapsed.

    Called at the start of each worker cycle.  Fetches new rules from
    Server A every ``_RULES_REFRESH_EVERY`` cycles to pick up learner
    updates without hammering the API.
    """
    global _cached_rules_text, _rules_refresh_counter

    _rules_refresh_counter += 1
    if _rules_refresh_counter >= _RULES_REFRESH_EVERY or _cached_rules_text is None:
        _cached_rules_text = _fetch_active_rules()
        _rules_refresh_counter = 0


def _build_prompt(title: str, summary: str) -> str:
    """Build the full LLM scoring prompt, optionally injecting learned rules.

    If the worker has cached scoring rules from the learner, they are
    prepended as a calibration section before the base scoring instructions.

    Args:
        title:   Article headline text.
        summary: Article summary text (may be empty/None).

    Returns:
        Formatted prompt string ready for the Ollama API.
    """
    parts = []

    # Inject learned rules section if available.
    if _cached_rules_text:
        parts.append(
            _RULES_SECTION_TEMPLATE.format(rules_text=_cached_rules_text)
        )

    # Base scoring prompt with article details filled in.
    parts.append(
        _LLM_PROMPT_BASE.format(
            title=title,
            summary=summary or "No summary available.",
        )
    )

    return "".join(parts)


# ---------------------------------------------------------------------------
# In-memory dedup set (resets on restart; DB dedup on Server A is authoritative)
# ---------------------------------------------------------------------------
_seen_urls: set = set()
_MAX_SEEN_URLS = 10_000  # Cap to prevent unbounded memory growth


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _is_market_hours() -> bool:
    """Check if US stock markets are currently open (9:30 AM – 4:00 PM ET, Mon–Fri).

    Uses a simplified check without holiday awareness.  The worker runs more
    frequently during these hours since news volume is highest.

    Returns:
        True if the current time falls within US market hours.
    """
    now_utc = datetime.now(timezone.utc)
    # US Eastern is UTC-5 (EST) or UTC-4 (EDT).  Use UTC-4 as a conservative
    # approximation (market hours effectively 13:30–20:00 UTC during EDT).
    hour_utc = now_utc.hour
    weekday = now_utc.weekday()  # 0=Monday, 6=Sunday

    # Skip weekends.
    if weekday >= 5:
        return False

    # Approximate EDT market hours: 13:30 – 20:00 UTC.
    if 13 <= hour_utc < 20:
        return True
    return False


def _score_with_ollama(title: str, summary: str) -> dict:
    """Call the local Ollama API to score a news article with the LLM.

    Builds a prompt from the article headline and summary (plus any learned
    calibration rules), sends it to the Ollama ``/api/generate`` endpoint,
    and parses the JSON response.

    Args:
        title:   Article headline text.
        summary: Article summary text (may be empty/None).

    Returns:
        Parsed dict with keys: general_score, general_reasoning, tickers.

    Raises:
        ValueError: If the LLM response cannot be parsed as valid JSON.
        requests.RequestException: On network/connection errors.
    """
    # Build the prompt with optional learned rules injection.
    prompt = _build_prompt(title, summary)

    payload = {
        "model": OLLAMA_MODEL,
        "prompt": prompt,
        "stream": False,
        "options": {
            "temperature": 0.1,   # Low temperature for deterministic scoring
            "num_predict": 512,   # Cap output length
        },
    }

    resp = requests.post(
        f"{OLLAMA_URL}/api/generate",
        json=payload,
        timeout=_OLLAMA_TIMEOUT,
    )
    resp.raise_for_status()

    raw_text = resp.json().get("response", "")

    # Attempt to extract JSON from the LLM output.  The model may wrap it
    # in markdown code fences or include preamble text.
    return _parse_llm_json(raw_text)


def _parse_llm_json(raw_text: str) -> dict:
    """Extract and parse a JSON object from raw LLM output.

    Handles common LLM quirks: markdown code fences, trailing commas,
    preamble text before the JSON block.

    Args:
        raw_text: Raw text response from the LLM.

    Returns:
        Parsed dict with validated structure.

    Raises:
        ValueError: If no valid JSON can be extracted.
    """
    text = raw_text.strip()

    # Strip markdown code fences if present.
    fence_match = re.search(r"```(?:json)?\s*\n?(.*?)\n?```", text, re.DOTALL)
    if fence_match:
        text = fence_match.group(1).strip()

    # Try to find a JSON object in the text.
    # Look for the outermost { ... } block.
    brace_start = text.find("{")
    if brace_start == -1:
        raise ValueError(f"No JSON object found in LLM response: {raw_text[:200]}")

    # Find the matching closing brace.
    depth = 0
    brace_end = -1
    for i in range(brace_start, len(text)):
        if text[i] == "{":
            depth += 1
        elif text[i] == "}":
            depth -= 1
            if depth == 0:
                brace_end = i
                break

    if brace_end == -1:
        raise ValueError(f"Unmatched braces in LLM response: {raw_text[:200]}")

    json_str = text[brace_start : brace_end + 1]

    # Remove trailing commas before } or ] (common LLM mistake).
    json_str = re.sub(r",\s*([}\]])", r"\1", json_str)

    try:
        data = json.loads(json_str)
    except json.JSONDecodeError as e:
        raise ValueError(
            f"Invalid JSON from LLM: {e}. Raw: {json_str[:200]}"
        ) from e

    # Validate and clamp the structure.
    return _validate_score(data)


def _validate_score(data: dict) -> dict:
    """Validate and sanitise the parsed LLM scoring output.

    Ensures scores are clamped to [-5, +5] and the structure matches what
    Server A's ingestion endpoint expects.

    Args:
        data: Parsed JSON dict from the LLM.

    Returns:
        Validated dict with correct types and ranges.
    """
    general_score = data.get("general_score", 0)
    if not isinstance(general_score, (int, float)):
        general_score = 0
    general_score = max(-5, min(5, int(general_score)))

    general_reasoning = data.get("general_reasoning", "")
    if not isinstance(general_reasoning, str):
        general_reasoning = ""

    tickers = []
    raw_tickers = data.get("tickers", [])
    if isinstance(raw_tickers, list):
        for t in raw_tickers:
            if not isinstance(t, dict):
                continue
            symbol = t.get("symbol", "").strip().upper()
            if not symbol or len(symbol) > 10:
                continue
            score = t.get("score", 0)
            if not isinstance(score, (int, float)):
                score = 0
            score = max(-5, min(5, int(score)))
            reasoning = t.get("reasoning", "")
            if not isinstance(reasoning, str):
                reasoning = ""
            tickers.append({
                "ticker": symbol,
                "score": score,
                "reasoning": reasoning[:500],  # Cap reasoning length
            })

    return {
        "general_score": general_score,
        "general_reasoning": general_reasoning[:500],
        "tickers": tickers,
    }


def _build_ingest_payload(article: dict, scores: dict) -> dict:
    """Combine a raw article dict with LLM scores into an ingestion payload.

    The payload matches the ``NewsArticleIngest`` schema expected by
    Server A's ``POST /api/v1/news/internal/news`` endpoint.

    Args:
        article: Article dict from sources.py (title, url, source, etc.).
        scores:  Validated LLM scoring dict (general_score, tickers, etc.).

    Returns:
        Dict ready to be JSON-serialised and POSTed to Server A.
    """
    return {
        "url": article["url"],
        "title": article["title"],
        "summary": article.get("summary"),
        "source": article["source"],
        "published_at": article.get("published_at"),
        "general_score": scores["general_score"],
        "general_reasoning": scores["general_reasoning"],
        "tickers": scores["tickers"],
    }


def _post_to_server_a(payloads: list) -> bool:
    """POST a batch of scored articles to Server A's ingestion endpoint.

    Args:
        payloads: List of article dicts matching NewsArticleIngest schema.

    Returns:
        True if the POST succeeded (2xx), False otherwise.
    """
    if not payloads:
        return True

    headers = {
        "Content-Type": "application/json",
        "X-Internal-Key": INTERNAL_KEY,
    }

    try:
        resp = requests.post(
            _INGEST_ENDPOINT,
            json=payloads,
            headers=headers,
            timeout=30,
        )
        if resp.ok:
            result = resp.json()
            logger.info(
                "Posted %d articles to Server A: inserted=%s, skipped=%s",
                len(payloads),
                result.get("inserted"),
                result.get("skipped"),
            )
            return True
        else:
            logger.error(
                "Server A rejected POST: status=%d, body=%s",
                resp.status_code,
                resp.text[:300],
            )
            return False
    except requests.RequestException as exc:
        logger.error("Failed to POST to Server A: %s", exc)
        return False


# ---------------------------------------------------------------------------
# Queue flush
# ---------------------------------------------------------------------------

def _flush_queue() -> None:
    """Attempt to deliver all pending articles from the local SQLite queue.

    Retrieves queued payloads, POSTs each individually to Server A, and
    updates the queue accordingly (mark done on success, increment retries
    on failure).
    """
    pending = article_queue.get_pending(limit=50)
    if not pending:
        return

    logger.info("Flushing %d pending articles from local queue...", len(pending))

    for row_id, payload_json in pending:
        try:
            payloads = json.loads(payload_json)
            # Ensure it's a list (single-article payloads are wrapped).
            if isinstance(payloads, dict):
                payloads = [payloads]

            success = _post_to_server_a(payloads)
            if success:
                article_queue.mark_done(row_id)
            else:
                article_queue.increment_retries(row_id)
        except Exception as exc:
            logger.error("Queue flush error for row %d: %s", row_id, exc)
            article_queue.increment_retries(row_id)


# ---------------------------------------------------------------------------
# Main cycle
# ---------------------------------------------------------------------------

def _run_cycle() -> None:
    """Execute one complete worker cycle: rules refresh → flush → fetch → score → post.

    This is the core business logic called repeatedly from the main loop.
    """
    global _seen_urls

    # 0. Refresh learned scoring rules from Server A (every N cycles).
    _maybe_refresh_rules()

    # 1. Flush any pending articles from the local queue first.
    _flush_queue()

    # 2. Fetch news from all sources.
    logger.info("Fetching news from all sources...")
    raw_articles = sources.fetch_all_news()
    logger.info("Fetched %d unique articles from sources.", len(raw_articles))

    if not raw_articles:
        logger.info("No articles fetched this cycle.")
        return

    # 3. Deduplicate against already-seen URLs (in-memory + Server A dedup).
    new_articles = []
    for article in raw_articles:
        url = article.get("url", "")
        if url and url not in _seen_urls:
            new_articles.append(article)
            _seen_urls.add(url)

    # Cap the seen set to prevent unbounded memory growth.
    if len(_seen_urls) > _MAX_SEEN_URLS:
        # Keep the most recent half.
        _seen_urls = set(list(_seen_urls)[_MAX_SEEN_URLS // 2 :])

    if not new_articles:
        logger.info("No new articles after dedup.")
        return

    # Limit to MAX_ARTICLES_PER_CYCLE to avoid overloading Ollama.
    articles_to_process = new_articles[:_MAX_ARTICLES_PER_CYCLE]
    logger.info(
        "Processing %d new articles (skipped %d already seen).",
        len(articles_to_process),
        len(raw_articles) - len(new_articles),
    )

    # 4. Score each article with the LLM and build ingestion payloads.
    scored_payloads = []
    for i, article in enumerate(articles_to_process, 1):
        title = article.get("title", "Untitled")
        logger.info(
            "[%d/%d] Scoring: %.80s",
            i,
            len(articles_to_process),
            title,
        )
        try:
            scores = _score_with_ollama(title, article.get("summary"))
            payload = _build_ingest_payload(article, scores)
            scored_payloads.append(payload)
        except ValueError as exc:
            logger.warning("LLM parse error for '%.60s': %s", title, exc)
            # Assign a neutral score rather than dropping the article entirely.
            payload = _build_ingest_payload(article, {
                "general_score": 0,
                "general_reasoning": "Unable to score — LLM parse failure.",
                "tickers": [],
            })
            scored_payloads.append(payload)
        except requests.RequestException as exc:
            logger.error("Ollama connection error for '%.60s': %s", title, exc)
            # Don't add to scored_payloads — can't score without the LLM.
            continue

    if not scored_payloads:
        logger.info("No articles scored this cycle.")
        return

    # 5. POST scored articles to Server A in batches.
    for batch_start in range(0, len(scored_payloads), _POST_BATCH_SIZE):
        batch = scored_payloads[batch_start : batch_start + _POST_BATCH_SIZE]
        success = _post_to_server_a(batch)
        if not success:
            # Queue each article individually for retry.
            for payload in batch:
                article_queue.enqueue(json.dumps(payload))
            logger.warning(
                "Queued %d articles locally (Server A unreachable).", len(batch)
            )


# ---------------------------------------------------------------------------
# Main loop
# ---------------------------------------------------------------------------

def main() -> None:
    """Entry point: initialise the queue DB and run the worker loop forever.

    The loop runs one cycle, then sleeps for 10 minutes during US market
    hours or 30 minutes during off-hours.  Any unhandled exception in a
    cycle is caught and logged so the worker doesn't crash.
    """
    logger.info("=" * 60)
    logger.info("TickerTap News Worker starting")
    logger.info("  Server A URL:  %s", API_URL)
    logger.info("  Ollama URL:    %s", OLLAMA_URL)
    logger.info("  Ollama model:  %s", OLLAMA_MODEL)
    logger.info("  Internal key:  %s", "SET" if INTERNAL_KEY else "NOT SET")
    logger.info("  Rules refresh: every %d cycles", _RULES_REFRESH_EVERY)
    logger.info("=" * 60)

    if not INTERNAL_KEY:
        logger.warning(
            "TICKERTAP_INTERNAL_KEY is not set! "
            "POSTs to Server A will be rejected."
        )

    # Initialise the local SQLite queue.
    article_queue.init_db()

    cycle_count = 0
    while True:
        cycle_count += 1
        logger.info("--- Cycle %d starting ---", cycle_count)

        try:
            _run_cycle()
        except Exception:
            logger.exception("Unhandled error in worker cycle %d.", cycle_count)

        # Determine sleep interval.
        if _is_market_hours():
            sleep_secs = _SLEEP_MARKET_HOURS
            logger.info(
                "Market hours — sleeping %d minutes. Pending queue: %d",
                sleep_secs // 60,
                article_queue.pending_count(),
            )
        else:
            sleep_secs = _SLEEP_OFF_HOURS
            logger.info(
                "Off-hours — sleeping %d minutes. Pending queue: %d",
                sleep_secs // 60,
                article_queue.pending_count(),
            )

        time.sleep(sleep_secs)


if __name__ == "__main__":
    main()
