"""Create score_outcomes and scoring_rules tables for the feedback loop.

Adds the tables required by the self-improving scoring system:
  - score_outcomes:  tracks actual stock price movements vs LLM predictions
  - scoring_rules:   stores versioned calibration rules generated by the learner

Revision ID: 0010_score_feedback
Revises: 0009_news_articles
Create Date: 2026-03-04
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID

revision = "0010_score_feedback"
down_revision = "0009_news_articles"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ── score_outcomes — tracks actual price movements vs LLM predictions ─────
    op.create_table(
        "score_outcomes",
        sa.Column(
            "outcome_id",
            UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "article_id",
            UUID(as_uuid=True),
            sa.ForeignKey("news_articles.article_id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("ticker", sa.String(20), nullable=False),
        # 'general' for SPY-based market score, 'ticker' for per-ticker score.
        sa.Column("score_type", sa.String(10), nullable=False),
        # Original LLM prediction (-5 to +5)
        sa.Column("predicted_score", sa.SmallInteger, nullable=False),
        sa.Column("predicted_reasoning", sa.Text, nullable=True),
        # Actual price data from yfinance
        sa.Column("price_at_score", sa.Numeric(18, 4), nullable=True),
        sa.Column("price_after", sa.Numeric(18, 4), nullable=True),
        sa.Column("actual_change_pct", sa.Numeric(10, 4), nullable=True),
        # Accuracy assessment: 'correct', 'close', 'wrong', 'opposite'
        sa.Column("accuracy_grade", sa.String(10), nullable=False),
        # Denormalised from the article for efficient learner queries.
        sa.Column(
            "scored_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "checked_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        # Constraints
        sa.UniqueConstraint(
            "article_id", "ticker", "score_type",
            name="uq_score_outcome_article_ticker",
        ),
        sa.CheckConstraint(
            "score_type IN ('general', 'ticker')",
            name="ck_score_outcomes_score_type",
        ),
        sa.CheckConstraint(
            "accuracy_grade IN ('correct', 'close', 'wrong', 'opposite')",
            name="ck_score_outcomes_grade",
        ),
        sa.CheckConstraint(
            "predicted_score BETWEEN -5 AND 5",
            name="ck_score_outcomes_predicted",
        ),
    )
    op.create_index(
        "idx_score_outcomes_article",
        "score_outcomes",
        ["article_id"],
    )
    op.create_index(
        "idx_score_outcomes_checked",
        "score_outcomes",
        [sa.text("checked_at DESC")],
    )
    op.create_index(
        "idx_score_outcomes_grade",
        "score_outcomes",
        ["accuracy_grade"],
    )
    op.create_index(
        "idx_score_outcomes_ticker",
        "score_outcomes",
        ["ticker"],
    )

    # ── scoring_rules — versioned calibration rules from the learner ──────────
    op.create_table(
        "scoring_rules",
        sa.Column(
            "rule_id",
            UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        # Monotonically increasing version number.
        sa.Column("rule_version", sa.Integer, nullable=False),
        # The rules text injected into the LLM scoring prompt.
        sa.Column("rules_text", sa.Text, nullable=False),
        # Summary of what the learner found in the data.
        sa.Column("analysis_summary", sa.Text, nullable=True),
        # Number of outcome records analysed when generating these rules.
        sa.Column("sample_size", sa.Integer, nullable=True),
        # Overall accuracy % at the time these rules were generated.
        sa.Column("accuracy_before", sa.Numeric(5, 2), nullable=True),
        # Only one rule set is active at any time.
        sa.Column(
            "is_active",
            sa.Boolean,
            nullable=False,
            server_default=sa.text("FALSE"),
        ),
        sa.Column(
            "generated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.UniqueConstraint("rule_version", name="uq_scoring_rules_version"),
    )
    # Partial index for fast "get active rules" lookup.
    op.create_index(
        "idx_scoring_rules_active",
        "scoring_rules",
        ["is_active"],
        postgresql_where=sa.text("is_active = TRUE"),
    )


def downgrade() -> None:
    op.drop_index("idx_scoring_rules_active", table_name="scoring_rules")
    op.drop_table("scoring_rules")

    op.drop_index("idx_score_outcomes_ticker", table_name="score_outcomes")
    op.drop_index("idx_score_outcomes_grade", table_name="score_outcomes")
    op.drop_index("idx_score_outcomes_checked", table_name="score_outcomes")
    op.drop_index("idx_score_outcomes_article", table_name="score_outcomes")
    op.drop_table("score_outcomes")
